language:
jdk:
- oraclejdk7
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -e

after_success:
- mvn clean  cobertura:cobertura  sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN


notifications:
  email:
    - 15838028035@163.com
